*** Starting uWSGI 1.0.3-debian (32bit) on [Sun Jun 10 13:24:16 2012] ***
compiled with version: 4.6.2 on 20 February 2012 10:06:16
current working directory: /etc/uwsgi/apps-enabled
detected binary path: /usr/bin/uwsgi-core
your memory page size is 4096 bytes
unlink(): Operation not permitted [socket.c line 75]
bind(): Address already in use [socket.c line 107]
*** Starting uWSGI 1.0.3-debian (32bit) on [Sun Jun 10 13:28:49 2012] ***
compiled with version: 4.6.2 on 20 February 2012 10:06:16
current working directory: /etc/uwsgi/apps-enabled
detected binary path: /usr/bin/uwsgi-core
your memory page size is 4096 bytes
uwsgi socket 0 bound to UNIX address /tmp/blog.sock fd 4
Python version: 2.7.3 (default, Apr 20 2012, 23:06:40)  [GCC 4.6.3]
Set PythonHome to /home/taras1k/.virtualenvs/blog
Python main interpreter initialized at 0x8deb5e0
your server socket listen backlog is limited to 100 connections
*** Operational MODE: single process ***
added /home/taras1k/Projects/blog_git/blog/ to pythonpath.
Traceback (most recent call last):
  File "/home/taras1k/Projects/blog_git/blog/main_app.py", line 4, in <module>
    import users
  File "/home/taras1k/Projects/blog_git/blog/users.py", line 5, in <module>
    import sensetive_info 
ImportError: No module named sensetive_info
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 4145)
spawned uWSGI worker 1 (pid: 4151, cores: 1)
[pid: 4151|app: -1|req: -1/1] 127.0.0.1 () {36 vars in 540 bytes} [Sun Jun 10 13:28:54 2012] GET / => generated 48 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 63 bytes (0 switches on core 0)
[pid: 4151|app: -1|req: -1/2] 127.0.0.1 () {36 vars in 540 bytes} [Sun Jun 10 13:29:08 2012] GET / => generated 48 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 63 bytes (0 switches on core 0)
[pid: 4151|app: -1|req: -1/3] 127.0.0.1 () {36 vars in 540 bytes} [Sun Jun 10 13:29:09 2012] GET / => generated 48 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 63 bytes (0 switches on core 0)
...brutally killing workers...
binary reloading uWSGI...
chdir() to /etc/uwsgi/apps-enabled
closing all non-uwsgi socket fds > 2 (_SC_OPEN_MAX = 1024)...
found fd 4 mapped to socket 0 (/tmp/blog.sock)
running /usr/bin/uwsgi-core
[uWSGI] getting YAML configuration from blog.yml
*** Starting uWSGI 1.0.3-debian (32bit) on [Sun Jun 10 16:22:42 2012] ***
compiled with version: 4.6.2 on 20 February 2012 10:06:16
current working directory: /etc/uwsgi/apps-enabled
detected binary path: /usr/bin/uwsgi-core
your memory page size is 4096 bytes
uwsgi socket 0 inherited UNIX address /tmp/blog.sock fd 4
Python version: 2.7.3 (default, Apr 20 2012, 23:06:40)  [GCC 4.6.3]
Set PythonHome to /home/taras1k/.virtualenvs/blog
Python main interpreter initialized at 0x9e5b4d8
your server socket listen backlog is limited to 100 connections
*** Operational MODE: single process ***
added /home/taras1k/Projects/blog_git/blog/ to pythonpath.
Traceback (most recent call last):
  File "/home/taras1k/Projects/blog_git/blog/main_app.py", line 4, in <module>
    import users
  File "/home/taras1k/Projects/blog_git/blog/users.py", line 4, in <module>
    from settings import connection
  File "/home/taras1k/Projects/blog_git/blog/settings.py", line 4, in <module>
    connection = Connection(auto_start_request=False) 
  File "/home/taras1k/.virtualenvs/blog/local/lib/python2.7/site-packages/pymongo/connection.py", line 290, in __init__
    self.__find_node()
  File "/home/taras1k/.virtualenvs/blog/local/lib/python2.7/site-packages/pymongo/connection.py", line 586, in __find_node
    raise AutoReconnect(', '.join(errors))
pymongo.errors.AutoReconnect: could not connect to localhost:27017: [Errno 111] Connection refused
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 4145)
spawned uWSGI worker 1 (pid: 5460, cores: 1)
